export const routes = {
  DETALLES: "/Detalles/:id",
  CATEGORIAS: "/Categorias/:id",
  HOME: "/",
  EXPLORE: "/Explore/",
  EXPLOREID: "/Explore/:id",
  EXPLORECATEGORY: "/ExploreCategory/:id",
  FREELANCERPROFILE: "/FreelancerProfile/:id",
  SERVICE: "/Service/:id",
  LOGIN: "/Login",
  LOGOUT: "/Logout",
  HOME_POST: "/Posts",
  CREATE_POST: "/NewPost",
  EDIT_POST: "/EditPost/:id",
  PRODUCTS: "/Products",
  TECH_DATA: "/DatosTecnicos",
  ABOUT_US: "/AboutUs",
  POSTS: "/Blog",
};
  