export const routes = {
  DETALLES: "/Detalles/:id",
  CATEGORIAS: "/Categorias/:id",
  HOME: "/",
  EXPLORE: "/Explore/",
  EXPLOREID: "/Explore/:id",
  EXPLORECATEGORY: "/ExploreCategory/:id",
  FREELANCERPROFILE: "/FreelancerProfile/:id",
  DASHBOARD_FREELANCER: "Freelancer",
  DASHBOARD_FREELANCERPROFILE: "Profile",
  DASHBOARD_FREELANCERSKILLS: "Skills",
  DASHBOARD_FREELANCEREDUCATION: "Education",
  DASHBOARD_FREELANCERCERTIFICATION: "Certification",
  DASHBOARD_FREELANCERWHYME: "WhyMe",
  SERVICE: "/Service/:id",
  LOGIN: "/Login",
  LOGOUT: "/Logout",
  HOME_POST: "/Posts",
  CREATE_POST: "/NewPost",
  EDIT_POST: "/EditPost/:id",
  PRODUCTS: "/Products",
  TECH_DATA: "/DatosTecnicos",
  ABOUT_US: "/AboutUs",
  POSTS: "/Blog",
};
  